project:
  type: website
  output-dir: docs

website:
  title: "Jay Liu"
  navbar:
  
    style: "floating"
    search: false
    left: 
      - href: index.qmd
        text: Home
      - about.qmd
    right: 
      - icon: linkedin
        href: https://www.linkedin.com/in/jay-liu-93a466389/
        aria-label: linkedin
      - icon: github
        href: https://github.com/JayIsTiredToday?tab=repositories
        aria-label: github

        

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



