project:
  type: website
  output-dir: docs

website:
  title: "Jay Liu"
  navbar:
    search: false
    background: "#FCAA83" 
    right: 
      - icon: linkedin
        href: https://www.linkedin.com/in/jay-liu-93a466389/
        aria-label: linkedin
      - icon: github
        href: https://github.com/JayIsTiredToday?tab=repositories
        aria-label: github
      - href: "projects.qmd"
        text: Projects


        

format:
  html:
    theme:
      - cosmo
      - brand
    backgroundcolor: "#E8E6E6"
    page-layout: article
    margin-left: 0px
    margin-right: 0px
    css: styles.css




